version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_USERNAME="root"
      - MYSQL_DATABASE=mydb
    ports:
      - 3307:3306
    networks:
      - mynetwork
  backend:
    image: devops
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8383:8383
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring.datasource.username = root
      - spring.datasource.password = ""
      - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
    volumes:
      - ./m2:/root/.m2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge